name: Build Kernel GKI 6.1

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Build Action
        uses: dabao1955/kernel_build_action@main
        with:
          kernel_source: 'https://android.googlesource.com/kernel/common'
          kernel_branch: 'android14-6.1'
          device_model: 'Tecno Pova 7 5G'
          aosp_clang: 'true'
          enable_ksu: 'true'
          ksu_type: 'ksu-next'
          ksu_branch: 'main'
          enable_susfs: 'true'
          susfs_branch: 'main'
